### ISSUE TITLE
tasks to bring this 100% 

### ISSUE THREAD

**Issue by basejump** [9ci/grails-view-tools#17] opened 2017-10-15 16:20 UTC
- [x] move integration test for appResource. As mentioned, we want to try as much as practical to keep integration tests out of the core and leave those in the test app examples. 
it should be testable in a unit test using doWithSpring and doWithConfig.  http://docs.grails.org/3.2.x/guide/testing.html. I've also noticed that some of the resource beans get setup with the controller mixins if need be. 

- [x]  copy the codenarc rules.groovy over from gorm-tools
- [x] bump the codenarc  maxPriorityViolations settings down so the errors are visible and review, fix or suppress them. 
- [x] the build status is missing from README. 
- [x] provide link to api from readme
- [x] provide any special build instructions for devs in readme. for examlple how to run mkdocs locally
- [x] add links for groovy doc source so its readable without the big long paths
```
groovydoc {
    excludes = ['**/*GrailsPlugin.groovy','**/Application.groovy' ]
    link('http://download.oracle.com/javase/8/docs/api/', 'java.', 'org.xml', 'javax.', 'org.xml.')
    link("https://docs.spring.io/spring/docs/4.2.x/javadoc-api/", 'org.springframework')
    link('http://groovy.codehaus.org/api/',  'groovy.', 'org.codehaus.groovy.')
    link('https://docs.grails.org/3.2.x/api',  'grails.', 'org.grails.')
    link('http://gorm.grails.org/latest/hibernate/api/',  'grails.gorm', 'org.grails.datastore', 'org.grails.orm')
}
```

**Comment by snimavat** [comment] 2017-10-16 12:05
Should be done, please review @basejump

**Comment by basejump** [comment] 2017-10-17 05:01
bring codenarc consistent with dao. get it out of the conf dir so it doesn't get packaged. both dao and graphql show where it should go. 
also, is there a reason some got commented out like noDef?

**Comment by snimavat** [comment] 2017-10-17 05:28
@noDef etc commented out because we have to use def for currentTenant closure
- createTempFile rule commented out because we need it.

**Comment by basejump** [comment] 2017-10-17 06:13
can we not have the appResrouceService test as unit test?

**Comment by snimavat** [comment] 2017-10-17 06:14
unit tests will be just duplicate of our integration tests, but we would set the config from doWithConfig. 
there arent domains etc involved, they wil do same thing, if its unit or integration...

**Closed as completed** 2017-10-17 07:42 UTC

**Comment by basejump** [comment] 2017-10-17 09:46
Its always better to do it in a unit if when we can. much faster of course and easier to understand. We can and should have both in this case

**Comment by basejump** [comment] 2017-10-17 09:47
but if we have both then they should not be testing for the same things really.
